language: ruby
rvm:
  - 1.9.0
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
notifications:
  email:
    recipients:
      - rubydev@textalk.se
    on_success: "never"
    on_failure: "always"
